name: Haskell CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: cachix/install-nix-action@v31
      - name: Format Haskell files
        run: MODE=check nix run .#scripts.run-fourmolu
  build:
    runs-on: ubuntu-latest
    needs: format
    env:
      default_compiler: ghc910
      default_package: mutagen
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - ghc96
          - ghc98
          - ghc910
          - ghc912
        package:
          - mutagen
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Nix
        uses: cachix/install-nix-action@v31
      - name: Build package
        run: |
          nix build \
            --print-build-logs \
            .#${{ matrix.compiler }}.${{ matrix.package }}
      - name: Prepare documentation artifact
        run: |
          mkdir _docs
          cp -rL result/share/doc/*/html/* _docs
          chmod -R u+w _docs
      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v4
        if: matrix.compiler == env.default_compiler && matrix.package == env.default_package
        id: haddock
        with:
          path: _docs
  deploy-pages:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: haddock
